language: python
sudo: false
python:
  - "2.7"
#  - "3.4"
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-yaml
    - python-tk
    # - python3-numpy
    # - python3-scipy
    # - python3-matplotlib
    # - python3-yaml
    # - python3-tk
virtualenv:
  system_site_packages: true
script: PYTHONPATH=$PWD/src py.test tests
cache:
  - apt