language: python
sudo: false
python:
  - "2.7"
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-yaml
    - python-tk
virtualenv:
  system_site_packages: true
script: PYTHONPATH=$PWD/src py.test tests
cache:
  - apt